---
- name: install apache
  become: true
  yum:
    name: "httpd"
    state: present

- name: install git
  become: true
  yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  git:
    repo: https://github.com/alagbaski/tooling.git
    dest: /home/ec2-user/
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /tooling/html/ /var/www/

- name: start service httpd, if not started
  become: true
  service:
    name: httpd
    state: started

- name: recursively remove /tooling directory
  become: true
  file:
    path: /home/ec2-user/tooling
    state: absent
