---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache
  become: yes

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}.load"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
    state: link
    mode: 0644
  with_items: "{{ apache_mods_enabled }}"
  notify: restart 
  become: yes

- name: Enable Apache modules
  ansible.builtin.shell:
    cmd: "a2enmod {{ item }}"
  loop:
    - rewrite
    - proxy
    - proxy_balancer
    - proxy_http
    - headers
    - lbmethod_byrequests
  notify: restart apache
  become: yes

# - name: Disable Apache mods.
#   file:
#     path: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
#     state: absent
#   with_items: "{{ apache_mods_disabled }}"
#   notify: restart apache

# - name: Check whether certificates defined in vhosts exist.
#   stat: "path={{ item.certificate_file }}"
#   register: apache_ssl_certificates
#   with_items: "{{ apache_vhosts_ssl }}"
#   no_log: "{{ apache_ssl_no_log }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool
  become: yes

# - name: Add vhost symlink in sites-enabled.
#   file:
#     src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
#     dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
#     state: link
#     mode: 0644
#     force: "{{ ansible_check_mode }}"
#   notify: restart apache
#   when: apache_create_vhosts | bool

# - name: Remove default vhost in sites-enabled.
#   file:
#     path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
#     state: absent
#   notify: restart apache
#   when: apache_remove_default_vhost

- name: Add load balancer settings to Apache vhosts configuration
  ansible.builtin.blockinfile:
    path: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - DO NOT EDIT"
    block: |
      <Proxy "balancer://mycluster">
         BalancerMember http://172.31.41.207:80 loadfactor=5 timeout=1
         BalancerMember http://172.31.43.146:80 loadfactor=5 timeout=1
         ProxySet lbmethod=byrequests
      </Proxy>
      ProxyPass "/" "balancer://mycluster/"
      ProxyPassReverse "/" "balancer://mycluster/"
    insertbefore: "</VirtualHost>"
  notify: restart apache
  become: yes
  ignore_errors: yes
