[nfs]
172.31.29.107 ansible_ssh_user=ec2-user

[webservers]
172.31.16.249 ansible_ssh_user=ec2-user
172.31.20.166 ansible_ssh_user=ec2-user

[db]
172.31.25.208 ansible_ssh_user=ubuntu

[lb]
172.31.18.126 ansible_ssh_user=ubuntu
