# - name: Add universe repository
#   ansible.builtin.apt_repository:
#     repo: 'deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe'
#     state: present
#   become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install dependencies
  ansible.builtin.apt:
    name: 
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
  become: yes

- name: Add PHP PPA
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php
    state: present
  become: yes

- name: Update apt cache after adding PHP PPA
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install Apache2 on the webserver
  ansible.builtin.apt:
    name: apache2
    state: present
  become: yes

- name: Ensure Apache2 is started and enabled
  become: yes
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Install PHP and related modules
  become: yes
  ansible.builtin.apt:
    name:
      - php7.4
      - php7.4-mysql
      - php7.4-gd
      - php7.4-curl
      - unzip
      - php7.4-common
      - php7.4-mbstring
      - php7.4-opcache
      - php7.4-intl
      - php7.4-xml
      - php7.4-fpm
      - php7.4-json
    state: present

- name: Ensure php7.4-fpm is started and enabled
  become: yes
  ansible.builtin.service:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Download the artifact
  become: yes
  ansible.builtin.get_url:
    url: http://13.42.10.206:8082/artifactory/todo-php-repo/php-todo.zip
    dest: /home/ubuntu/php-todo.zip
    url_username: admin
    url_password: Admin123

- name: Unzip the artifacts
  become: yes
  ansible.builtin.unarchive:
    src: /home/ubuntu/php-todo.zip
    dest: /home/ubuntu/
    remote_src: yes

- name: Run chmod on /var/www/html
  become: yes
  remote_user: ubuntu
  ansible.builtin.command:
    cmd: sudo chown -R $USER:$USER /var/www/html

- name: Deploy the code
  remote_user: ubuntu
  become: yes
  ansible.builtin.copy:
    src: /home/ubuntu/var/lib/jenkins/workspace/php-todo_main/
    dest: /var/www/html/
    force: yes
    remote_src: yes

- name: Delete the zip file after unzipping
  become: yes
  ansible.builtin.file:
    path: /home/ubuntu/php-todo.zip
    state: absent

- name: Delete the unzipped files after copying
  become: yes
  ansible.builtin.file:
    path: /home/ubuntu/var/
    state: absent

- name: Remove Apache2 default page
  remote_user: ubuntu
  become: yes
  ansible.builtin.file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: Restart Apache2
  become: yes
  ansible.builtin.service:
    name: apache2
    state: restarted
