# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- import_playbook: "../dynamic-assignments/env-vars.yml"
  tags:
    - always

- hosts: all
  name: Common configuration
  import_playbook: "../static-assignments/common.yml"

- hosts: webservers
  name: Webserver assignment
  import_playbook: "../static-assignments/uat-webservers.yml"

- hosts: lb
  name: Loadbalancers assignment
  import_playbook: "../static-assignments/loadbalancers.yml"
  when: load_balancer_is_required
