# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- name: Include dynamic variables
  hosts: all
  tasks:
    - import_playbook: "../dynamic-assignments/env-vars.yml"
  tags:
    - always

- name: Common configuration
  hosts: all
  import_playbook: "../static-assignments/common.yml"

- name: Webserver assignment
  hosts: webservers
  import_playbook: "../static-assignments/uat-webservers.yml"

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: "../static-assignments/loadbalancers.yml"
  when: load_balancer_is_required
