# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- name: Include dynamic variables
  hosts: all
  become: yes
  tasks:
    - include_vars: ../dynamic-assignments/env-vars.yml
      tags:
        - always

# - hosts: mysql_servers
#   become: yes
#   roles:
#     - mysql

# - import_playbook: ../static-assignments/common.yml

- name: Webservers Tasks
  ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

- name:
  ansible.builtin.import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_true