# ---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yml

# - hosts: uat-webservers
# - import_playbook: ../static-assignments/uat-webservers.yml

---
- name: Include dynamic variables
  hosts: all
  tasks:
    - include_vars: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- import_playbook: ../static-assignments/common.yml

- import_playbook: ../static-assignments/uat-webservers.yml

- name: Loadbalancers assignment
- hosts: lb
- import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required

- hosts: db-servers
  become: yes
  roles:
    - mysql